package golden.raspberry.awards.adapter.driving.rest.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.*;

/**
 * DTO for creating a new movie (request body).
 * Using Java 21 record for immutability and extreme elegance.
 *
 * <p>Follows Richardson Level 2: structured request format.
 * Does not include ID (generated by database).
 *
 * <p>Uses Java 21 features EXTREMELY:
 * <ul>
 *   <li>Records with compact constructor</li>
 *   <li>String Templates for elegant error messages</li>
 *   <li>Sealed interfaces for validation results</li>
 *   <li>Pattern Matching for validation</li>
 *   <li>Stream API for functional validation</li>
 *   <li>Method references for clean code</li>
 * </ul>
 *
 * @author Luiz Generoso
 * @since 1.0.0
 */
public record CreateMovieDTO(
        @JsonProperty("year")
        @NotNull(message = "Field 'year' is required and cannot be null")
        @Min(value = 1900, message = "Field 'year' must be at least 1900")
        Integer year,

        @JsonProperty("title")
        @NotNull(message = "Field 'title' is required and cannot be null")
        @NotBlank(message = "Field 'title' cannot be empty or contain only whitespace")
        @Size(min = 2, max = 255, message = "Field 'title' must be between 2 and 255 characters")
        String title,

        @JsonProperty("studios")
        @NotNull(message = "Field 'studios' is required and cannot be null")
        @NotBlank(message = "Field 'studios' cannot be empty or contain only whitespace")
        @Size(min = 2, max = 255, message = "Field 'studios' must be between 2 and 255 characters")
        String studios,

        @JsonProperty("producers")
        @NotNull(message = "Field 'producers' is required and cannot be null")
        @NotBlank(message = "Field 'producers' cannot be empty or contain only whitespace")
        @Size(min = 2, max = 255, message = "Field 'producers' must be between 2 and 255 characters")
        String producers,

        @JsonProperty("winner")
        @NotNull(message = "Field 'winner' is required and cannot be null")
        Boolean winner
) {
    /**
     * Compact constructor with Java 21 features.
     * Trims string fields automatically.
     *
     * @param year      Movie release year (validated by Jakarta Validation)
     * @param title     Movie title (validated by Jakarta Validation)
     * @param studios   Movie studios (validated by Jakarta Validation)
     * @param producers Movie producers (validated by Jakarta Validation)
     * @param winner    Whether the movie is a winner (validated by Jakarta Validation)
     */
    public CreateMovieDTO {
        if (title != null) {
            title = title.trim();
        }
        if (studios != null) {
            studios = studios.trim();
        }
        if (producers != null) {
            producers = producers.trim();
        }
    }

}
