package golden.raspberry.awards.core.domain.model;

import org.springframework.lang.NonNull;

import java.util.Objects;

/**
 * Domain model for Movie with ID.
 * Used when Movie needs to be identified after persistence.
 *
 * <p>This is a Domain model that includes the ID generated by the persistence layer.
 * It is used by Application layer to work with persisted movies that have IDs.
 *
 * <p>Uses Java 21 features: Records, String Templates.
 *
 * @author Luiz Generoso
 * @since 1.0.0
 */
public record MovieWithId(
        @NonNull Long id,
        @NonNull Integer year,
        @NonNull String title,
        @NonNull String studios,
        @NonNull String producers,
        @NonNull Boolean winner
) {
    /**
     * Compact constructor with validation.
     *
     * @param id        Movie ID (non-null)
     * @param year      Movie release year (non-null)
     * @param title     Movie title (non-null, non-blank)
     * @param studios   Movie studios (non-null, non-blank)
     * @param producers Movie producers (non-null, non-blank)
     * @param winner    Whether the movie is a winner (non-null)
     * @throws IllegalArgumentException if validation fails
     */
    public MovieWithId {
        Objects.requireNonNull(id, "ID cannot be null");
        Objects.requireNonNull(year, "Year cannot be null");
        Objects.requireNonNull(title, "Title cannot be null");
        Objects.requireNonNull(studios, "Studios cannot be null");
        Objects.requireNonNull(producers, "Producers cannot be null");
        Objects.requireNonNull(winner, "Winner cannot be null");

        if (title.isBlank()) {
            throw new IllegalArgumentException("Title cannot be blank");
        }
        if (studios.isBlank()) {
            throw new IllegalArgumentException("Studios cannot be blank");
        }
        if (producers.isBlank()) {
            throw new IllegalArgumentException("Producers cannot be blank");
        }
        if (year < 1900 || year > 2100) {
            throw new IllegalArgumentException(
                    "Year must be between 1900 and 2100, but was: %d".formatted(year)
            );
        }

        title = title.trim();
        studios = studios.trim();
        producers = producers.trim();
    }

    /**
     * Converts MovieWithId to Movie (domain model without ID).
     *
     * @return Movie domain model
     */
    public Movie toMovie() {
        return new Movie(year, title, studios, producers, winner);
    }
}

